#!/usr/bin/python3 
from sage.all import *

p = 2**256 - 2**224 + 2**192 + 2**96 - 1
F = GF(p)
a = -3
n = 115792089210356248762697446949407573529996955224135760342422259061068512044369
prod = 1
ar = []
# find small b'
# Lagrange's Theorem that order of the subgroup generated by any point on a curve is a divisor of the cardinality of that curve.
for b in range(1, 20):
    if b == 2:
        # singular
        continue
    E = EllipticCurve(F, [a, b])
    G = E.gen(0)
    od = G.order()
    fac = od.factor()
    subgroups = [
        f ** e for f, e in fac if gcd(f ** e, prod) == 1 and f ** e < 2**40
    ]  # very small
    ar.append((b, G.xy(), od, subgroups))
    prod = lcm(prod, product(subgroups))
    if prod > n:
        break


print(ar)